version: "3"
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
    - ./database:/data/db
  server:
    build: server/
    ports:
      - "3000:3000"
    links:
      - mongo
  client:
    build: client/
    ports:
      - "8080:8080"
    depends_on:
      - server
