version: "3"
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    networks:
      - app-network
    volumes:
    - ./database:/data/db

  server:
    build: server/
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mongo
    links:
      - mongo

  client:
    build: client/
    networks:
      - app-network
    ports:
      - "8080:8080"
networks:
  app-network:
    driver: bridge